export const OCR_ENDPOINT = "OCR_ENDPOINT";
export const BIO_ENDPOINT = "BIO_ENDPOINT";
export const ENROLL_ENDPOINT = "ENROLL_ENDPOINT";
export const DUKCAPIL_ENDPOINT = "DUKCAPIL_ENDPOINT";
export const LOCAL_VERIFY_ENDPOINT = "LOCAL_VERIFY_ENDPOINT";
export const IS_LOGIN = "IS_LOGIN";
export const ACCESS_TOKEN = "ACCESS_TOKEN";
